import { NextRequest, NextResponse } from "next/server";
import { generateVideoWithRetry } from "@/lib/falService";
import { generateVideoPromptFromSession } from "@/lib/promptGenerator";
import { uploadVideoToBlob } from "@/lib/blobStorage";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { turns, riteOfPassage, sessionId, songUrl } = body;

    if (!turns || !Array.isArray(turns)) {
      return NextResponse.json(
        { error: "Invalid request: turns array required" },
        { status: 400 }
      );
    }

    console.log(`🎬 Generating video for session ${sessionId || "unknown"}...`);

    // Always generate AI video, with or without audio
    if (songUrl) {
      console.log(
        "🎵 Song detected - will generate AI video with audio mixing"
      );
    } else {
      console.log("🎬 No song found - will generate AI video without audio");
    }

    // Step 1: Generate comprehensive video prompt from all conversation
    const promptResult = await generateVideoPromptFromSession(
      turns,
      riteOfPassage
    );

    console.log("Generated video prompt:", promptResult.videoPrompt);

    // Step 2: Generate video with Fal.ai (with retry)
    console.log("⏱️ Generating 10-second video (may take 60-90 seconds)...");

    const videoResult = await generateVideoWithRetry({
      prompt: promptResult.videoPrompt,
      duration: 10, // Always 10 seconds (maximum for seedance/lite model)
      aspectRatio: "16:9",
    });

    // Step 3: Handle result
    if (videoResult && videoResult.video) {
      console.log("✅ Video generated by Fal.ai");

      // Step 4: Download from Fal.ai and upload to Vercel Blob for permanent storage
      const falVideoUrl = videoResult.video.url;
      console.log("📥 Downloading and uploading video to Vercel Blob...");

      const permanentUrl = await uploadVideoToBlob(falVideoUrl, sessionId);

      console.log("✅ Video stored permanently at:", permanentUrl);

      return NextResponse.json({
        success: true,
        videoUrl: permanentUrl, // Return permanent Vercel Blob URL
        prompt: promptResult.videoPrompt,
        keywords: promptResult.keywords,
        era: promptResult.era,
        location: promptResult.location,
        metadata: {
          fileName: videoResult.video.file_name,
          fileSize: videoResult.video.file_size,
          contentType: videoResult.video.content_type,
          seed: videoResult.seed,
          originalFalUrl: falVideoUrl, // Keep original for debugging
        },
      });
    } else {
      // Video generation failed after retries
      console.error("⚠️ Video generation failed after retries");

      return NextResponse.json(
        {
          success: false,
          error: "Video generation failed after retries",
          prompt: promptResult.videoPrompt,
        },
        { status: 500 }
      );
    }
  } catch (error: unknown) {
    console.error("❌ Video generation API error:", error);
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";

    return NextResponse.json(
      {
        success: false,
        error: errorMessage,
      },
      { status: 500 }
    );
  }
}
